version: "3.8"
services:
    db:
        build: ./
        environment:
            SA_PASSWORD: msSqlserver123
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - published: 1433
              target: 1433
        volumes:
            - ms-sqlserver-linux-data:/var/opt/mssql:rw
            - ./backup:/backup:rw
volumes:
    ms-sqlserver-linux-data:
        driver: local
